# Generated by Django 6.0.3 on 2026-05-27 18:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(blank=True, help_text="Emoji icon", max_length=10),
                ),
                ("unit", models.CharField(default="per quintal", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "commodities",
                "db_table": "market_commodities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(blank=True, default="", max_length=120)),
                (
                    "country",
                    models.CharField(blank=True, default="Ethiopia", max_length=100),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "change",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=200)),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="market.commodity",
                    ),
                ),
            ],
            options={
                "db_table": "market_prices",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["commodity", "-recorded_at"],
                        name="market_pric_commodi_987c14_idx",
                    ),
                    models.Index(
                        fields=["country", "-recorded_at"],
                        name="market_pric_country_09e401_idx",
                    ),
                ],
            },
        ),
    ]
